name: Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build:
          - linux musl x64
          - linux musl aarch64
          - macos x64
          - macos aarch64
          - pc windows msvc x64
        include:
          - build: linux musl x64
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            cargo: cargo
            build_dir: "target/release"
          - build: linux musl aarch64
            os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-musl
            cargo: cross
            build_dir: "target/x86_64-unknown-linux-gnu/release"
          - build: macos x64
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            cargo: cargo
            build_dir: "target/release"
          - build: macos aarch64
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            cargo: cargo
            build_dir: "target/release"
          - build: pc windows msvc x64
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            cargo: cargo
            build_dir: "target/release"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Use Cross
        if: matrix.cargo == 'cross'
        shell: bash
        run: |
          # In the past, new releases of 'cross' have broken CI. So for now, we
          # pin it. We also use their pre-compiled binary releases because cross
          # has over 100 dependencies and takes a bit to compile.
          dir="$RUNNER_TEMP/cross-download"
          mkdir "$dir"
          echo "$dir" >> $GITHUB_PATH
          cd "$dir"
          curl -LO "https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz"
          tar xf cross-x86_64-unknown-linux-musl.tar.gz

      - name: Install musl-tools
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y --no-install-recommends musl-tools
        
      # Workaround for <https://github.com/actions/virtual-environments/issues/2557>
      - name: Switch Xcode SDK
        shell: bash
        if: runner.os == 'macos'
        run: |
          cat <<EOF >> "$GITHUB_ENV"
          SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
          EOF

      - name: Build release binary
        shell: bash
        run: |
          ${{ matrix.cargo }} build --verbose --release
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            filename="obs-countdown.exe"
          else
            filename="obs-countdown"
          fi
          bin="${{ matrix.build_dir }}/$filename"
          echo "BIN=$bin" >> $GITHUB_ENV
          echo "FILENAME=$filename" >> $GITHUB_ENV

      - name: List build artifacts
        run: ls -R target/

      - name: Create checksum
        shell: bash
        id: make-checksum
        working-directory: ./${{ matrix.build_dir }}
        run: |
          name="obs-countdown-${{ matrix.target }}.sha256sum"
          if [[ "$RUNNER_OS" != "macOS" ]]; then
            sha256sum "${{ env.FILENAME }}" > "${name}"
          else
            shasum -a 256 "${{ env.FILENAME }}" > "${name}"
          fi
          asset_sha_path=$(realpath "${name}")
          echo "ASSET_SHA_PATH=$asset_sha_path" >> $GITHUB_ENV

      - name: Tar release
        shell: bash
        id: make-artifact
        working-directory: ./${{ matrix.build_dir }}
        run: |
          name="obs-countdown-${{ matrix.target }}.tar.gz"
          tar cvzf "${name}" ${{ env.FILENAME }}
          asset_path=$(realpath "${name}")
          echo "ASSET_PATH=$asset_path" >> $GITHUB_ENV

      - name: Prints assets paths
        run: |
          ls -al ${{ env.ASSET_PATH }}
          ls -al ${{ env.ASSET_SHA_PATH }}

      - name: Upload release archive
        uses: actions/upload-release-asset@v1.0.2
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: obs-countdown-${{matrix.target}}.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload checksum
        uses: actions/upload-release-asset@v1.0.2
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ${{ env.ASSET_SHA_PATH }}
          asset_name: obs-countdown-${{matrix.target}}.sha256sum
          asset_content_type: text/plain

  release-on-crates-io:
    needs:
        - build-release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Release on Crates.io
          run: |
              cargo login ${{ secrets.CARGO_TOKEN }}
              cargo publish